#define ISHC_ID 0x02
#define ISDC_ID 0x10
#define ISEC_ID 0x04

#define MEASURE_PH "MEASURE_PH"
#define MEASURE_CONDUCT "MEASURE_CONDUCT"
#define MEASURE_RESIS "MEASURE_RESIS"
#define MEASURE_SALI "MEASURE_SALI"
#define MEASURE_TDS "MEASURE_TDS"
#define MEASURE_DO "MEASURE_DO"
#define MEASURE_TEMP "MEASURE_TEMP"
